  openshell-cluster-openshell:
    image: ghcr.io/nvidia/openshell/cluster:0.0.16
    container_name: openshell-cluster-openshell
    restart: unless-stopped
    privileged: true
    command:
      - --plaintext
      - --disable-gateway-auth
    volumes:
      - openshell_data:/var/lib/rancher/k3s
    environment:
      - K3S_KUBECONFIG_MODE=644
